version: "3.4"
# To build images, run:
# docker compose -f docker-compose-x86_64.yml build

# Find MOFED_VERSION per OS and arch:
# https://network.nvidia.com/products/infiniband-drivers/linux/mlnx_ofed/

# Find NV_DRIVER_VERSION per CUDA version, OS and arch:
# https://developer.nvidia.com/cuda-11-7-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=runfile_local

services:
  centos7-mofed5-cuda11:
    image: centos7-mofed5-cuda11:3
    build:
      context: .
      network: host
      dockerfile: centos-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        MOFED_OS: rhel7.6
        CUDA_VERSION: 11.4.0
        OS_VERSION: 7
        ARCH: x86_64
  centos8-mofed5-cuda11:
    image: centos8-mofed5-cuda11:3
    build:
      context: .
      network: host
      dockerfile: centos-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        MOFED_OS: rhel8.2
        CUDA_VERSION: 11.4.0
        OS_VERSION: 8
        ARCH: x86_64
  ubuntu18.04-mofed5-cuda11:
    image: ubuntu18.04-mofed5-cuda11:3
    build:
      context: .
      network: host
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        UBUNTU_VERSION: 18.04
        CUDA_VERSION: 11.4.0
        NV_DRIVER_VERSION: 470
        ARCH: x86_64
  ubuntu20.04-mofed5-cuda11:
    image: ubuntu20.04-mofed5-cuda11:3
    build:
      context: .
      network: host
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        UBUNTU_VERSION: 20.04
        CUDA_VERSION: 11.4.0
        NV_DRIVER_VERSION: 470
        ARCH: x86_64
  ubuntu22.04-mofed5-cuda11:
    image: ubuntu22.04-mofed5-cuda11:3
    build:
      context: .
      network: host
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.4-3.6.8.1
        UBUNTU_VERSION: 22.04
        CUDA_VERSION: 11.7.0
        NV_DRIVER_VERSION: 515
        ARCH: x86_64
  centos7-mofed5-cuda12:
    image: centos7-mofed5-cuda12:3
    build:
      context: .
      network: host
      dockerfile: centos-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        MOFED_OS: rhel7.6
        CUDA_VERSION: 12.0.0
        OS_VERSION: 7
        ARCH: x86_64
  ubuntu18.04-mofed5-cuda12:
    image: ubuntu18.04-mofed5-cuda12:3
    build:
      context: .
      network: host
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        UBUNTU_VERSION: 18.04
        CUDA_VERSION: 12.0.0
        NV_DRIVER_VERSION: 525
        ARCH: x86_64
  ubuntu20.04-mofed5-cuda12:
    image: ubuntu20.04-mofed5-cuda12:3
    build:
      context: .
      network: host
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.0-1.0.0.0
        UBUNTU_VERSION: 20.04
        CUDA_VERSION: 12.0.0
        NV_DRIVER_VERSION: 525
        ARCH: x86_64
  ubuntu22.04-mofed5-cuda12:
    image: ubuntu22.04-mofed5-cuda12:3
    build:
      context: .
      network: host
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.4-3.6.8.1
        UBUNTU_VERSION: 22.04
        CUDA_VERSION: 12.0.0
        NV_DRIVER_VERSION: 525
        ARCH: x86_64
  ubuntu24.04-mofed5-cuda12:
    image: ubuntu24.04-mofed24.10-cuda12.5:1
    build:
      context: .
      network: host
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 24.10-1.1.4.0
        UBUNTU_VERSION: 24.04
        CUDA_VERSION: 12.5.1
        NV_DRIVER_VERSION: 555
        ARCH: x86_64
  ubuntu22.04-mofed5-cuda13:
    image: ubuntu22.04-mofed5-cuda13:1
    build:
      context: .
      network: host
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 5.8-7.0.6.1
        UBUNTU_VERSION: 22.04
        CUDA_VERSION: 13.0.0
        NV_DRIVER_VERSION: 580
        ARCH: x86_64
  ubuntu24.04-mofed5-cuda13:
    image: ubuntu24.04-mofed24.10-cuda13:1
    build:
      context: .
      network: host
      dockerfile: ubuntu-release.Dockerfile
      args:
        MOFED_VERSION: 24.10-3.2.5.0
        UBUNTU_VERSION: 24.04
        CUDA_VERSION: 13.0.0
        NV_DRIVER_VERSION: 580
        ARCH: x86_64
